
-- First: Update canton based on city name (safe, no casting)
UPDATE leads SET canton = 'Zürich', canton_code = 'ZH' WHERE (canton = '' OR canton_code = '') AND city IN ('Zürich','Winterthur','Dübendorf','Uster','Wetzikon','Küsnacht','Zollikon','Meilen','Thalwil','Kilchberg','Horgen','Wädenswil','Urdorf','Birmensdorf','Affoltern am Albis','Schlieren','Dietikon','Volketswil','Kloten','Opfikon','Bülach','Illnau-Effretikon','Adliswil','Regensdorf','Wallisellen','Rüti','Stäfa','Oberglatt','Turbenthal','Embrach','Männedorf','Egg','Maur','Langnau am Albis','Oberrieden','Pfäffikon','Richterswil','Hinwil');
UPDATE leads SET canton = 'Bern', canton_code = 'BE' WHERE (canton = '' OR canton_code = '') AND city IN ('Bern','Thun','Biel/Bienne','Burgdorf','Interlaken','Spiez','Langenthal','Münsingen','Steffisburg','Köniz','Ostermundigen','Ittigen','Muri bei Bern','Worb','Belp','Lyss','Zollikofen','Bolligen');
UPDATE leads SET canton = 'Luzern', canton_code = 'LU' WHERE (canton = '' OR canton_code = '') AND city IN ('Luzern','Kriens','Emmenbrücke','Ebikon','Horw','Emmen','Sursee','Rothenburg','Meggen');
UPDATE leads SET canton = 'Basel-Stadt', canton_code = 'BS' WHERE (canton = '' OR canton_code = '') AND city IN ('Basel','Riehen');
UPDATE leads SET canton = 'Basel-Landschaft', canton_code = 'BL' WHERE (canton = '' OR canton_code = '') AND city IN ('Allschwil','Muttenz','Pratteln','Liestal','Reinach','Binningen','Oberwil','Münchenstein');
UPDATE leads SET canton = 'St. Gallen', canton_code = 'SG' WHERE (canton = '' OR canton_code = '') AND city IN ('St. Gallen','Wil','Rapperswil-Jona','Gossau','Rorschach','Buchs','Uzwil');
UPDATE leads SET canton = 'Aargau', canton_code = 'AG' WHERE (canton = '' OR canton_code = '') AND city IN ('Aarau','Baden','Wettingen','Brugg','Lenzburg','Wohlen','Rheinfelden','Oftringen','Zofingen','Muhen','Mellingen','Muri','Suhr','Windisch','Oberentfelden','Frick','Spreitenbach','Möhlin','Aargau');
UPDATE leads SET canton = 'Genf', canton_code = 'GE' WHERE (canton = '' OR canton_code = '') AND city IN ('Genève','Genf','Carouge','Vernier','Lancy','Meyrin');
UPDATE leads SET canton = 'Waadt', canton_code = 'VD' WHERE (canton = '' OR canton_code = '') AND city IN ('Lausanne','Prilly','Pully','Renens','Vevey','Montreux','Yverdon-les-Bains','Nyon','Morges');
UPDATE leads SET canton = 'Tessin', canton_code = 'TI' WHERE (canton = '' OR canton_code = '') AND city IN ('Bellinzona','Lugano','Locarno','Giubiasco','Mendrisio','Chiasso');
UPDATE leads SET canton = 'Solothurn', canton_code = 'SO' WHERE (canton = '' OR canton_code = '') AND city IN ('Solothurn','Olten','Grenchen','Zuchwil','Derendingen');
UPDATE leads SET canton = 'Freiburg', canton_code = 'FR' WHERE (canton = '' OR canton_code = '') AND city IN ('Fribourg','Freiburg','Bulle','Düdingen','Murten');
UPDATE leads SET canton = 'Thurgau', canton_code = 'TG' WHERE (canton = '' OR canton_code = '') AND city IN ('Frauenfeld','Kreuzlingen','Weinfelden','Amriswil','Arbon');
UPDATE leads SET canton = 'Graubünden', canton_code = 'GR' WHERE (canton = '' OR canton_code = '') AND city IN ('Chur','Davos','St. Moritz','Landquart');
UPDATE leads SET canton = 'Wallis', canton_code = 'VS' WHERE (canton = '' OR canton_code = '') AND city IN ('Sion','Brig','Zermatt','Visp','Martigny','Sierre','Monthey','Naters');
UPDATE leads SET canton = 'Neuenburg', canton_code = 'NE' WHERE (canton = '' OR canton_code = '') AND city IN ('Neuchâtel','La Chaux-de-Fonds');
UPDATE leads SET canton = 'Schwyz', canton_code = 'SZ' WHERE (canton = '' OR canton_code = '') AND city IN ('Schwyz','Lachen','Freienbach','Einsiedeln');
UPDATE leads SET canton = 'Zug', canton_code = 'ZG' WHERE (canton = '' OR canton_code = '') AND city IN ('Zug','Cham','Baar','Steinhausen');
UPDATE leads SET canton = 'Schaffhausen', canton_code = 'SH' WHERE (canton = '' OR canton_code = '') AND city IN ('Schaffhausen');
UPDATE leads SET canton = 'Appenzell I.Rh.', canton_code = 'AI' WHERE (canton = '' OR canton_code = '') AND city IN ('Appenzell');
UPDATE leads SET canton = 'Appenzell A.Rh.', canton_code = 'AR' WHERE (canton = '' OR canton_code = '') AND city IN ('Herisau','Teufen');
UPDATE leads SET canton = 'Uri', canton_code = 'UR' WHERE (canton = '' OR canton_code = '') AND city IN ('Altdorf','Erstfeld');
UPDATE leads SET canton = 'Obwalden', canton_code = 'OW' WHERE (canton = '' OR canton_code = '') AND city IN ('Sarnen','Engelberg');
UPDATE leads SET canton = 'Nidwalden', canton_code = 'NW' WHERE (canton = '' OR canton_code = '') AND city IN ('Stans','Hergiswil','Buochs');
UPDATE leads SET canton = 'Glarus', canton_code = 'GL' WHERE (canton = '' OR canton_code = '') AND city IN ('Glarus','Näfels');
UPDATE leads SET canton = 'Jura', canton_code = 'JU' WHERE (canton = '' OR canton_code = '') AND city IN ('Delémont','Porrentruy');

-- Now PLZ-based updates (only for numeric PLZ values)
UPDATE leads SET canton = 'Zürich', canton_code = 'ZH' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8000 AND 8499;
UPDATE leads SET canton = 'Zürich', canton_code = 'ZH' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8600 AND 8639;
UPDATE leads SET canton = 'Zürich', canton_code = 'ZH' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8650 AND 8749;
UPDATE leads SET canton = 'Zürich', canton_code = 'ZH' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8760 AND 8852;
UPDATE leads SET canton = 'Zürich', canton_code = 'ZH' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8854 AND 8999;
UPDATE leads SET canton = 'Bern', canton_code = 'BE' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 2500 AND 2699;
UPDATE leads SET canton = 'Bern', canton_code = 'BE' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 3000 AND 3899;
UPDATE leads SET canton = 'Luzern', canton_code = 'LU' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 6000 AND 6299;
UPDATE leads SET canton = 'Aargau', canton_code = 'AG' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 5000 AND 5999;
UPDATE leads SET canton = 'Basel-Stadt', canton_code = 'BS' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 4000 AND 4099;
UPDATE leads SET canton = 'Basel-Landschaft', canton_code = 'BL' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 4100 AND 4199;
UPDATE leads SET canton = 'Basel-Landschaft', canton_code = 'BL' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 4400 AND 4499;
UPDATE leads SET canton = 'Solothurn', canton_code = 'SO' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 4500 AND 4999;
UPDATE leads SET canton = 'St. Gallen', canton_code = 'SG' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 9000 AND 9049;
UPDATE leads SET canton = 'St. Gallen', canton_code = 'SG' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 9060 AND 9099;
UPDATE leads SET canton = 'St. Gallen', canton_code = 'SG' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 9200 AND 9699;
UPDATE leads SET canton = 'St. Gallen', canton_code = 'SG' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int = 8640;
UPDATE leads SET canton = 'Zug', canton_code = 'ZG' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 6300 AND 6399;
UPDATE leads SET canton = 'Schwyz', canton_code = 'SZ' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 6400 AND 6459;
UPDATE leads SET canton = 'Schwyz', canton_code = 'SZ' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int = 8853;
UPDATE leads SET canton = 'Uri', canton_code = 'UR' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 6460 AND 6499;
UPDATE leads SET canton = 'Tessin', canton_code = 'TI' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 6500 AND 6999;
UPDATE leads SET canton = 'Graubünden', canton_code = 'GR' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 7000 AND 7799;
UPDATE leads SET canton = 'Schaffhausen', canton_code = 'SH' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8200 AND 8279;
UPDATE leads SET canton = 'Thurgau', canton_code = 'TG' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8280 AND 8289;
UPDATE leads SET canton = 'Thurgau', canton_code = 'TG' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8500 AND 8599;
UPDATE leads SET canton = 'Glarus', canton_code = 'GL' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 8750 AND 8759;
UPDATE leads SET canton = 'Appenzell I.Rh.', canton_code = 'AI' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 9050 AND 9059;
UPDATE leads SET canton = 'Appenzell A.Rh.', canton_code = 'AR' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 9100 AND 9199;
UPDATE leads SET canton = 'Genf', canton_code = 'GE' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 1200 AND 1299;
UPDATE leads SET canton = 'Waadt', canton_code = 'VD' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 1000 AND 1199;
UPDATE leads SET canton = 'Waadt', canton_code = 'VD' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 1300 AND 1499;
UPDATE leads SET canton = 'Waadt', canton_code = 'VD' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 1800 AND 1899;
UPDATE leads SET canton = 'Freiburg', canton_code = 'FR' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 1500 AND 1799;
UPDATE leads SET canton = 'Wallis', canton_code = 'VS' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 1900 AND 1999;
UPDATE leads SET canton = 'Wallis', canton_code = 'VS' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 3900 AND 3999;
UPDATE leads SET canton = 'Neuenburg', canton_code = 'NE' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 2000 AND 2499;
UPDATE leads SET canton = 'Jura', canton_code = 'JU' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 2800 AND 2999;
UPDATE leads SET canton = 'Obwalden', canton_code = 'OW' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 6060 AND 6078;
UPDATE leads SET canton = 'Nidwalden', canton_code = 'NW' WHERE (canton = '' OR canton_code = '') AND plz ~ '^\d{4}$' AND plz::int BETWEEN 6370 AND 6390;
